/*********\
| General |######################################################################################################################################################################\
|                                                                                                                                                                                |
|     Situation:                # Function:                                                                                                                                      |                 
|    ###################################################                                                                                                                         |                               
|     Hue To Scriptvar          # getInfo, getInfoAll                                                                                                                            |                                                                                                                     
|     Scriptvar to Hue          # setInfo, setInfoAll                                                                                                                            |                                                                                                                       
|     From Hue                  # get[Variable]                                                                                                                                  |                                                                                               
|     To Hue                    # set[Variable]                                                                                                                                  |                                                                                               
|     return                                                                                                                                                                     |                                                             
|     return                                                                                                                                                                     |                                                             
|     From disk                 # loadInfo, loadInfoALL                                                                                                                          |                                                                                                                     
|     To disk                   # saveInfo, saveInfoAll                                                                                                                          |                                                                                                                     
|     From/To script            # not needed                                                                                                                                     |                                                                                             
|                                                                                                                                                                                |                                                                        |
*********************************************************************************************************************************************************************************/
debug = false;



/*********\
| getInfo |######################################################################################################################################################################\
|                                                                                                                                                                                |
| - get all attributes for 1 sensor, from hue to script-variables                                                                                                                |
|                                                                                                                                                                                |
|  Example: sensor.getInfo(iLightNumber, Value)                                                                                                                                  |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
exports.getInfo = function( iSensorNumber,sValue){
  client.getSensor( iSensorNumber, function( err, result ){ 

    if ( err || result === undefined || result.state === undefined ){ return err;}
    
    //General:
    if ( typeof result.manufacturername !== undefined      ){ sArraySensorManufacturerName[iSensorNumber] = result.manufacturername;    };  
    if ( typeof result.modelid !== undefined               ){ sArraySensorModelId[iSensorNumber] = result.modelid;                      };  
    if ( typeof result.name !== undefined                  ){ sArraySensorName[iSensorNumber] = result.name;                            };  
    if ( typeof result.swversion !== undefined             ){ sArraySensorSwVersion[iSensorNumber] = result.swversion;                  };  
    if ( typeof result.type !== undefined                  ){ sArraySensorType[iSensorNumber] = result.type;                            };  
    if ( typeof result.uniqueid !== undefined              ){ sArraySensorUniqueId[iSensorNumber] = result.uniqueid;                    };  
                                                                                                                                            
    //State:
    if ( typeof result.state.lightlevel !== undefined      ){ iArraySensorLightLevel[iSensorNumber] = result.state.lightlevel;          };
    if ( typeof result.state.dark !== undefined            ){ bArraySensorDark[iSensorNumber] = result.state.dark;                      };
    if ( typeof result.state.daylight !== undefined        ){ bArraySensorDaylight[iSensorNumber] = result.state.daylight;              };
    if ( typeof result.state.status !== undefined          ){ iArraySensorStatus[iSensorNumber] = result.state.status;                  };
    if ( typeof result.state.lastupdated !== undefined     ){ sArraySensorLastupdated[iSensorNumber] = result.state.lastupdated;        };
    if ( typeof result.state.presence !== undefined        ){ bArraySensorPresence[iSensorNumber] = result.state.presence;              };
    if ( typeof result.state.temperature !== undefined     ){ iArraySensorTemperature[iSensorNumber] = result.state.temperature;        };

    //Config:
    if ( typeof result.config.on !== undefined             ){ bArraySensorOn[iSensorNumber] = result.config.on;                         };
    if ( typeof result.config.battery  !== undefined       ){ iArraySensorBattery[iSensorNumber] = result.config.battery;               };
    if ( typeof result.config.configured !== undefined     ){ bArraySensorConfigured[iSensorNumber] = result.config.configured;         };
    if ( typeof result.config.reachable !== undefined      ){ bArraySensorReachable[iSensorNumber] = result.config.reachable;           };
    if ( typeof result.config.alert !== undefined          ){ sArraySensorAlert[iSensorNumber] = result.config.alert;                   };
    if ( typeof result.config.tholddark !== undefined      ){ iArraySensorTholdDark[iSensorNumber] = result.config.tholddark;           };
    if ( typeof result.config.tholdoffset !== undefined    ){ iArraySensorTholdOffset[iSensorNumber] = result.config.tholdoffset;       };
    if ( typeof result.config.ledindication !== undefined  ){ bArraySensorLedindication[iSensorNumber] = result.config.ledindication;   };
    if ( typeof result.config.usertest !== undefined       ){ bArraySensorUsertest[iSensorNumber] = result.config.usertest;             };
    if ( typeof result.config.sensitivity !== undefined    ){ iArraySensorSensitivity[iSensorNumber] = result.config.sensitivity;       };
    if ( typeof result.config.sensitivitymax !== undefined ){ iArraySensorSensitivityMax[iSensorNumber] = result.config.sensitivitymax; };
    if ( typeof result.config.sunsetoffset !== undefined   ){ iArraySensorSunsetoffset[iSensorNumber] = result.config.sunsetoffset;     };
    if ( typeof result.config.sunriseoffset !== undefined  ){ iArraySensorSunriseoffset[iSensorNumber] = result.config.sunriseoffset;   };
    if ( typeof result.config.pending !== undefined        ){ sArraySensorPending[iSensorNumber] = result.config.pending;               };

    //Recycle:
    if ( typeof result.recycle !== undefined               ){ bArraySensorRecycle[iSensorNumber] = result.recycle;                      };
  });
};



/***************\
| getInfo - ALL |################################################################################################################################################################\
|                                                                                                                                                                                |
| - get all attributes for all sensors from hue to script-variables                                                                                                              |
|                                                                                                                                                                                |
|  Example: sensor.getInfoAll()                                                                                                                                                  |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
exports.getInfoAll = function(){
  //process.stdout.write('\n' + " Fetch Sensor Info...");
  var x = 1;
  getInfoAllDo();

  function getInfoAllDo(){
    if ( x > iArraySensorConnected.length ){ return; }
    sensor.getInfo(iArraySensorConnected[x++]);
    setTimeout(getInfoAllDo, 10);
  }
}



/*********\
| setInfo |######################################################################################################################################################################\
|                                                                                                                                                                                |
| - sets all attributes from 1 sensor from script-variables to hue                                                                                                               |
|                                                                                                                                                                                |
|  Example: sensor.setInfo( iSensorNumber,sValue )                                                                                                                               |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
exports.setInfo = function( iSensorNumber ){
  var result;
  //bOn = typeof bOn !== 'undefined' ? bOn : true;
  // parameterinfo-state   : "buttonevent, dark, daylight, lastupdated, lightlevel, presence, temperature" are not modifiable, only "status" is modifiable
  // parameterinfo-config  : "configured, reachable, sensitivitymax" are not available, further "on, sunriseoffset, sunsetoffset, battery, alert, ledindication, usertest, pending, sensitivity, tholddark, tholdoffset" is modifiable
  // client.changeSensorConfig( iSensorNumber, {}, function( err, result ){ if ( err) throw err; console.log(result); });
  //  client.changeSensorState( iSensorNumber, {}, function( err, result ){ if ( err) throw err; console.log(result); });
  //result = false; switch (iSensorNumber) { case 1:; result=true;default:if (!result) break; COMMAND; };
  
  console.log("Start Test");

  //                                                                                                                                           if ( sArraySensorManufacturerName[iSensorNumber] !== undefined ){                                                        "manufacturername": sArraySensorManufacturerName[iSensorNumber]    }, function( err, result ){ if ( err) throw err; console.log(result); }); };         //Read-Only            //  "manufacturername": sArraySensorManufacturerName[iSensorNumber]                                                                                                              
  //                                                                                                                                           if ( sArraySensorManufacturerName[iSensorNumber] !== undefined ){                                                        "manufacturername": sArraySensorManufacturerName[iSensorNumber]    }, function( err, result ){ if ( err) throw err; console.log(result); }); };         //Read-Only            //  "productname": sArraySensorProductName[iSensorNumber]                                                                                                              
  //                                                                                                                                           if ( sArraySensorModelId[iSensorNumber] !== undefined ){                                                                 "modelid": sArraySensorModelId[iSensorNumber]                      }, function( err, result ){ if ( err) throw err; console.log(result); }); };         //Read-Only            //  "modelid": sArraySensorModelId[iSensorNumber]                                                                                                                       
  //                                                                                                                                           if ( sArraySensorName[iSensorNumber] !== undefined ){                                                                    "name": sArraySensorName[iSensorNumber]                            }, function( err, result ){ if ( err) throw err; console.log(result); }); };         //Read-Only            //  "name": sArraySensorName[iSensorNumber]                                                                                                                          
  //                                                                                                                                           if ( sArraySensorSwVersion[iSensorNumber] !== undefined ){                                                               "swversion": sArraySensorSwVersion[iSensorNumber]                  }, function( err, result ){ if ( err) throw err; console.log(result); }); };         //Read-Only            //  "swversion": sArraySensorSwVersion[iSensorNumber]                                                                                                                     
  //                                                                                                                                           if ( sArraySensorType[iSensorNumber] !== undefined ){                                                                    "type": sArraySensorType[iSensorNumber]                            }, function( err, result ){ if ( err) throw err; console.log(result); }); };         //Read-Only            //  "type": sArraySensorType[iSensorNumber]                                                                                                                          
  //                                                                                                                                           if ( sArraySensorUniqueId[iSensorNumber] !== undefined ){                                                                "uniqueid": sArraySensorUniqueId[iSensorNumber]                    }, function( err, result ){ if ( err) throw err; console.log(result); }); };         //Read-Only            //  "uniqueid": sArraySensorUniqueId[iSensorNumber]                                                                                                               
  //result = false; switch (iSensorNumber) { case 2:;case 9:;case 10:;case 11:; result=true;default:if (!result) break;                        if ( bArraySensorRecycle[iSensorNumber] !== undefined ){                                                                 "recycle": bArraySensorRecycle[iSensorNumber]                      }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only            //  "recycle": bArraySensorRecycle[iSensorNumber]                                                                                                                 
  //result = false; switch (iSensorNumber) { case 5:; result=true;default:if (!result) break;                                                  if ( iArraySensorButtonEvent[iSensorNumber] !== undefined ){                 client.changeSensorConfig( iSensorNumber, { "buttonevent": iArraySensorButtonEvent[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only Config     //  "buttonevent": iArraySensorButtonEvent[iSensorNumber]                                                                
  //result = false; switch (iSensorNumber) { case 8:; result=true;default:if (!result) break;                                                  if ( iArraySensorLightLevel[iSensorNumber] !== undefined ){                  client.changeSensorConfig( iSensorNumber, { "lightlevel": iArraySensorLightLevel[iSensorNumber]                }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only Config     //  "lightlevel": iArraySensorLightLevel[iSensorNumber]                                                                   
  //result = false; switch (iSensorNumber) { case 8:; result=true;default:if (!result) break;                                                  if ( bArraySensorDark[iSensorNumber] !== undefined ){                        client.changeSensorConfig( iSensorNumber, { "dark": bArraySensorDark[iSensorNumber]                            }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only Config     //  "dark": bArraySensorDark[iSensorNumber]                                                                    
  //result = false; switch (iSensorNumber) { case 8:; result=true;default:if (!result) break;                                                  if ( bArraySensorDaylight[iSensorNumber] !== undefined ){                    client.changeSensorConfig( iSensorNumber, { "daylight": bArraySensorDaylight[iSensorNumber]                    }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only Config     //  "daylight": bArraySensorDaylight[iSensorNumber]                                                                    
  result = false; switch (iSensorNumber) { case 2:;case 9:;result=true;default:if (!result) break;                                             if ( iArraySensorStatus[iSensorNumber] !== undefined ){                      client.changeSensorState(  iSensorNumber, { "status": iArraySensorStatus[iSensorNumber]                        }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "status": iArraySensorStatus[iSensorNumber]                                                              
  //                                                                                                                                           if ( sArraySensorLastupdated[iSensorNumber] !== undefined ){                 client.changeSensorConfig( iSensorNumber, { "lastupdated": sArraySensorLastupdated[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only Config     //  "lastupdated": sArraySensorLastupdated[iSensorNumber]                                                               
  //result = false; switch (iSensorNumber) {  case 7:;case 10:; case 11:; result=true;default:if (!result) break;                              if ( bArraySensorPresence[iSensorNumber] !== undefined ){                    client.changeSensorConfig( iSensorNumber, { "presence": bArraySensorPresence[iSensorNumber]                    }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only Config     //  "presence": bArraySensorPresence[iSensorNumber]                                                               
  //result = false; switch (iSensorNumber) { case 6:; result=true;default:if (!result) break;                                                  if ( iArraySensorTemperature[iSensorNumber] !== undefined ){                 client.changeSensorConfig( iSensorNumber, { "temperature": iArraySensorTemperature[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only Config     //  "temperature": iArraySensorTemperature[iSensorNumber]                                                               
                                                                                                                                               if ( bArraySensorOn[iSensorNumber] !== undefined ){                          client.changeSensorState(  iSensorNumber, { "on": bArraySensorOn[iSensorNumber]                                }, function( err, result ){ if ( err) throw err; console.log(result); }); ;}         //Enabled State        //  "on": bArraySensorOn[iSensorNumber]                                                                 
  result = false; switch (iSensorNumber) { case 2:;case 6:;case 7:;case 8:;result=true;default:if (!result) break;                             if ( iArraySensorBattery[iSensorNumber] !== undefined ){                     client.changeSensorConfig( iSensorNumber, { "battery": iArraySensorBattery[iSensorNumber]                      }, function( err, result ){ if ( err) throw err; console.log(result); }); ;} };      //Enabled State        //  "battery": iArraySensorBattery[iSensorNumber]                                                                
  //result = false; switch (iSensorNumber) { case 1:;result=true;default:if (!result) break;                                                   if ( bArraySensorConfigured[iSensorNumber] !== undefined ){                  client.changeSensorState(  iSensorNumber, { "configured": bArraySensorConfigured[iSensorNumber]                }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only state      //  "configured": bArraySensorConfigured[iSensorNumber]                                                              
  //result = false; switch (iSensorNumber) { case 2:;case 6:;case 7:;case 8:;case 9:;case 10:;case 11:;result=true;default:if (!result) break; if ( bArraySensorReachable[iSensorNumber] !== undefined ){                   client.changeSensorState(  iSensorNumber, { "reachable": bArraySensorReachable[iSensorNumber]                  }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only state      //  "reachable": bArraySensorReachable[iSensorNumber]                                                                     
  result = false; switch (iSensorNumber) { case 6:;case 7:;case 8:;result=true;default:if (!result) break;                                     if ( sArraySensorAlert[iSensorNumber] !== undefined ){                       client.changeSensorConfig( iSensorNumber, { "alert": sArraySensorAlert[iSensorNumber]                          }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "alert": sArraySensorAlert[iSensorNumber]                                                                   
  result = false; switch (iSensorNumber) { case 8:;result=true;default:if (!result) break;                                                     if ( iArraySensorTholdDark[iSensorNumber] !== undefined ){                   client.changeSensorConfig( iSensorNumber, { "tholddark": iArraySensorTholdDark[iSensorNumber]                  }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "tholddark": iArraySensorTholdDark[iSensorNumber]                                                                 
  result = false; switch (iSensorNumber) { case 8:;result=true;default:if (!result) break;                                                     if ( iArraySensorTholdOffset[iSensorNumber] !== undefined ){                 client.changeSensorConfig( iSensorNumber, { "tholdoffset": iArraySensorTholdOffset[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "tholdoffset": iArraySensorTholdOffset[iSensorNumber]                                                              
  result = false; switch (iSensorNumber) { case 6:;case 7:;case 8:;result=true;default:if (!result) break;                                     if ( bArraySensorLedindication[iSensorNumber] !== undefined ){               client.changeSensorConfig( iSensorNumber, { "ledindication": bArraySensorLedindication[iSensorNumber]          }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "ledindication": bArraySensorLedindication[iSensorNumber]                                                              
  result = false; switch (iSensorNumber) { case 6:;case 7:;case 8:;result=true;default:if (!result) break;                                     if ( bArraySensorUsertest[iSensorNumber] !== undefined ){                    client.changeSensorConfig( iSensorNumber, { "usertest": bArraySensorUsertest[iSensorNumber]                    }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "usertest": bArraySensorUsertest[iSensorNumber]                                                              
  result = false; switch (iSensorNumber) { case 7:;result=true;default:if (!result) break;                                                     if ( iArraySensorSensitivity[iSensorNumber] !== undefined ){                 client.changeSensorConfig( iSensorNumber, { "sensitivity": iArraySensorSensitivity[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "sensitivity": iArraySensorSensitivity[iSensorNumber]                                                              
  //result = false; switch (iSensorNumber) { case 7:;result=true;default:if (!result) break;                                                   if ( iArraySensorSensitivityMax[iSensorNumber]!== undefined ){               client.changeSensorConfig( iSensorNumber, { "sensitivitymax": iArraySensorSensitivityMax[iSensorNumber]        }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Read-Only state      //  "sensitivitymax": iArraySensorSensitivityMax[iSensorNumber]                                                              
  result = false; switch (iSensorNumber) { case 1:;result=true;default:if (!result) break;                                                     if ( iArraySensorSunriseoffset[iSensorNumber] !== undefined ){               client.changeSensorConfig( iSensorNumber, { "sunriseoffset": iArraySensorSunriseoffset[iSensorNumber]          }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "sunriseoffset": iArraySensorSunriseoffset[iSensorNumber]                                                              
  result = false; switch (iSensorNumber) { case 1:;result=true;default:if (!result) break;                                                     if ( iArraySensorSunsetoffset[iSensorNumber] !== undefined ) {               client.changeSensorConfig( iSensorNumber, { "sunsetoffset": iArraySensorSunsetoffset[iSensorNumber]            }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "sunsetoffset": iArraySensorSunsetoffset[iSensorNumber]                                                              
  result = false; switch (iSensorNumber) { case 6:;case 7:;case 8:;result=true;default:if (!result) break;                                     if ( sArraySensorPending[iSensorNumber] !== undefined ){                     client.changeSensorConfig( iSensorNumber, { "pending": sArraySensorPending[iSensorNumber]                      }, function( err, result ){ if ( err) throw err; console.log(result); }); }; };      //Enabled State        //  "pending": sArraySensorPending[iSensorNumber]                                                              
};

/***************\
| setInfo - ALL |################################################################################################################################################################\
|                                                                                                                                                                                |
| - sets all attributes for all sensors from script-variables to hue                                                                                                             |
|                                                                                                                                                                                |
|  Example: sensor.setInfoAll()                                                                                                                                                  |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
exports.setInfoAll = function(){
  //process.stdout.write('\n' + " Push Sensor Info...");
  var x = 1;
  setInfoAllDo();

  function setInfoAllDo(){
    if ( x > iArraySensorConnected.length ){ return; }
    sensor.setInfo(iArraySensorConnected[x++]);
    setTimeout(setInfoAllDo, 10);
  }
}



/**********\
| getValue |#####################################################################################################################################################################\
|                                                                                                                                                                                |
| - get attribute from a single sensor                                                                                                                                           |
|                                                                                                                                                                                |
|  Examples: sensor.getManufacturerName('1', function(callback){ console.log(callback); });                                                                                      |                                                                                              
|            sensor.getModelId('1', function(callback){ console.log(callback); });                                                                                               |                                                                                                                                                                                
|            sensor.getName('1', function(callback){ console.log(callback); });                                                                                                  |                                                                                  
|            sensor.getSwVersion('1', function(callback){ console.log(callback); });                                                                                             |                                                                                       
|            sensor.getType('1', function(callback){ console.log(callback); });                                                                                                  |                                                                                  
|            sensor.getUniqueid('1', function(callback){ console.log(callback); });                                                                                              |                                                                                      
|            sensor.getRecycle('1', function(callback){ console.log(callback); });                                                                                               |                                                                                
|            sensor.getButtonevent('1', function(callback){ console.log(callback); });                                                                                           |                                                                                 
|            sensor.getLightLevel('1', function(callback){ console.log(callback); });                                                                                            |                                                                                 
|            sensor.getDark('1', function(callback){ console.log(callback); });                                                                                                  |                                                                                 
|            sensor.getDaylight('1', function(callback){ console.log(callback); });                                                                                              |                                                                                    
|            sensor.getStatus('1', function(callback){ console.log(callback); });                                                                                                |                                                                                
|            sensor.getLastupdated('1', function(callback){ console.log(callback); });                                                                                           |                                                                                 
|            sensor.getPresence('1', function(callback){ console.log(callback); });                                                                                              |                                                                                 
|            sensor.getTemperature('1', function(callback){ console.log(callback); });                                                                                           |                                                                                
|            sensor.getOn('1', function(callback){ console.log(callback); });                                                                                                    |                                                                                                                                                                                                                                                                         
|            sensor.getBattery('1', function(callback){ console.log(callback); });                                                                                               |                                                                                       
|            sensor.getConfigured('1', function(callback){ console.log(callback); });                                                                                            |                                                                                       
|            sensor.getReachable('1', function(callback){ console.log(callback); });                                                                                             |                                                                                       
|            sensor.getAlert('1', function(callback){ console.log(callback); });                                                                                                 |                                                                                       
|            sensor.getTholdDark('1', function(callback){ console.log(callback); });                                                                                             |                                                                                       
|            sensor.getTholdOffset('1', function(callback){ console.log(callback); });                                                                                           |                                                                                       
|            sensor.getLedindication('1', function(callback){ console.log(callback); });                                                                                         |                                                                                       
|            sensor.getUsertest('1', function(callback){ console.log(callback); });                                                                                              |                                                                                       
|            sensor.getSensitivity('1', function(callback){ console.log(callback); });                                                                                           |                                                                                       
|            sensor.getSensitivitymax('1', function(callback){ console.log(callback); });                                                                                        |                                                                                       
|            sensor.getSunsetoffset('1', function(callback){ console.log(callback); });                                                                                          |                                                                                       
|            sensor.getUnriseoffset('1', function(callback){ console.log(callback); });                                                                                          |                                                                                       
|            sensor.getPending('1', function(callback){ console.log(callback); });                                                                                               |                                                                                       
|                                                                                                                                                                                |
|                                                                                                                                                                                |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
exports.getManufacturerName = function (iSensorNumber, callback ){ client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.manufacturername      === undefined ){ return err;} callback(result.manufacturername     ) } )}
exports.getProductName = function (iSensorNumber, callback ){      client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.productname           === undefined ){ return err;} callback(result.productname          ) } )}
exports.getModelId = function (iSensorNumber, callback ){          client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.modelid               === undefined ){ return err;} callback(result.modelid              ) } )}
exports.getName = function (iSensorNumber, callback ){             client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.name                  === undefined ){ return err;} callback(result.name                 ) } )}
exports.getSwVersion = function (iSensorNumber, callback ){        client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.swversion             === undefined ){ return err;} callback(result.swversion            ) } )}
exports.getType = function (iSensorNumber, callback ){             client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.type                  === undefined ){ return err;} callback(result.type                 ) } )}
exports.getUniqueid = function (iSensorNumber, callback ){         client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.uniqueid              === undefined ){ return err;} callback(result.uniqueid             ) } )}
exports.getRecycle = function (iSensorNumber, callback ){          client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.recycle               === undefined ){ return err;} callback(result.recycle              ) } )}                                                                                                                                                                                                                                                                                                   
exports.getButtonevent = function (iSensorNumber, callback ){      client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.state.buttonevent     === undefined ){ return err;} callback(result.state.buttonevent    ) } )}
exports.getLightLevel = function (iSensorNumber, callback ){       client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.state.lightlevel      === undefined ){ return err;} callback(result.state.lightlevel     ) } )}
exports.getDark = function (iSensorNumber, callback ){             client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.state.dark            === undefined ){ return err;} callback(result.state.dark           ) } )}
exports.getDaylight = function (iSensorNumber, callback ){         client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.state.daylight        === undefined ){ return err;} callback(result.state.daylight       ) } )}
exports.getStatus = function (iSensorNumber, callback ){           client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.state.status          === undefined ){ return err;} callback(result.state.status         ) } )}
exports.getLastupdated = function (iSensorNumber, callback ){      client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.state.lastupdated     === undefined ){ return err;} callback(result.state.lastupdated    ) } )}
exports.getPresence = function (iSensorNumber, callback ){         client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.state.presence        === undefined ){ return err;} callback(result.state.presence       ) } )}
exports.getTemperature = function (iSensorNumber, callback ){      client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.state.temperature     === undefined ){ return err;} callback(result.state.temperature    ) } )}
exports.getOn = function (iSensorNumber, callback ){               client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.on             === undefined ){ return err;} callback(result.config.on            ) } )}
exports.getBattery = function (iSensorNumber, callback ){          client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.battery        === undefined ){ return err;} callback(result.config.battery       ) } )}
exports.getConfigured = function (iSensorNumber, callback ){       client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.configured     === undefined ){ return err;} callback(result.config.configured    ) } )}
exports.getReachable = function (iSensorNumber, callback ){        client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.reachable      === undefined ){ return err;} callback(result.config.reachable     ) } )}
exports.getAlert = function (iSensorNumber, callback ){            client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.alert          === undefined ){ return err;} callback(result.config.alert         ) } )}
exports.getTholdDark = function (iSensorNumber, callback ){        client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.tholddark      === undefined ){ return err;} callback(result.config.tholddark     ) } )}
exports.getTholdOffset = function (iSensorNumber, callback ){      client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.tholdoffset    === undefined ){ return err;} callback(result.config.tholdoffset   ) } )}
exports.getLedindication = function (iSensorNumber, callback ){    client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.ledindication  === undefined ){ return err;} callback(result.config.ledindication ) } )}
exports.getUsertest = function (iSensorNumber, callback ){         client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.usertest       === undefined ){ return err;} callback(result.config.usertest      ) } )}
exports.getSensitivity = function (iSensorNumber, callback ){      client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.sensitivity    === undefined ){ return err;} callback(result.config.sensitivity   ) } )}
exports.getSensitivitymax = function (iSensorNumber, callback ){   client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.sensitivitymax === undefined ){ return err;} callback(result.config.sensitivitymax) } )}
exports.getSunsetoffset = function (iSensorNumber, callback ){     client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.sunsetoffset   === undefined ){ return err;} callback(result.config.sunsetoffset  ) } )}
exports.getUnriseoffset = function (iSensorNumber, callback ){     client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.sunriseoffset  === undefined ){ return err;} callback(result.config.sunriseoffset ) } )}
exports.getPending = function (iSensorNumber, callback ){          client.get('/sensors/' + iSensorNumber + '/', function (err, result) { if ( err || typeof result.config.pending        === undefined ){ return err;} callback(result.config.pending       ) } )}



/**********\
| setValue |#####################################################################################################################################################################\
|                                                                                                                                                                                |
| - set attribute from a single light                                                                                                                                            |
|                                                                                                                                                                                |
|  Example: sensor.getManufacturerName(iSensorNumber, Value)                                                                                                                     |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
//exports.setManufacturerName function ( iSensorNumber, Value ){  if (iSensorNumber !== 0 ){                                                                                                                if ( sArraySensorManufacturerName[iSensorNumber] !== undefined ){     client.changeSensor      ( iSensorNumber, { "manufacturername": sArraySensorManufacturerName[iSensorNumber]    }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only       "manufacturername": sArraySensorManufacturerName[iSensorNumber]
//exports.setProductName    = function ( iSensorNumber, Value ){  if (iSensorNumber !== 0 ){                                                                                                                if ( sArraySensorProductName[iSensorNumber] !== undefined ){          client.changeSensor      ( iSensorNumber, { "productname": sArraySensorProductName[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only       
//exports.setModelId        = function ( iSensorNumber, Value ){  if (iSensorNumber !== 0 ){                                                                                                                if ( sArraySensorModeId[iSensorNumber] !== undefined ){               client.changeSensor      ( iSensorNumber, { "modelid": sArraySensorModeId[iSensorNumber]                       }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only       
//exports.setName           = function ( iSensorNumber, Value ){  if (iSensorNumber !== 0 ){                                                                                                                if ( sArraySensorName[iSensorNumber] !== undefined ){                 client.changeSensor      ( iSensorNumber, { "name": sArraySensorName[iSensorNumber]                         }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only       
//exports.setSwVersion      = function ( iSensorNumber, Value ){  if (iSensorNumber !== 0 ){                                                                                                                if ( sArraySensorSwVersion[iSensorNumber] !== undefined ){            client.changeSensor      ( iSensorNumber, { "swversion": sArraySensorSwVersion[iSensorNumber]                  }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only       
//exports.setType           = function ( iSensorNumber, Value ){  if (iSensorNumber !== 0 ){                                                                                                                if ( sArraySensorType[iSensorNumber] !== undefined ){                 client.changeSensor      ( iSensorNumber, { "type": sArraySensorType[iSensorNumber]                            }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only       
//exports.setUniqueid       = function ( iSensorNumber, Value ){  if (iSensorNumber !== 0 ){                                                                                                                if ( sArraySensorUniqueId[iSensorNumber] !== undefined ){             client.changeSensor      ( iSensorNumber, { "uniqueid": sArraySensorUniqueId[iSensorNumber]                    }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only       
//exports.setRecycle        = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 2:;case 9:;case 10:;case 11:; result=true;default:if (!result) break;                        if ( bArraySensorRecycle[iSensorNumber] !== undefined ){              client.changeSensor      ( iSensorNumber, { "recycle": bArraySensorRecycle[iSensorNumber]                      }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only       
//exports.setButtonevent    = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 5:; result=true;default:if (!result) break;                                                  if ( iArraySensorButtonEvent[iSensorNumber] !== undefined ){          client.changeSensorConfig( iSensorNumber, { "buttonevent": iArraySensorButtonEvent[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only Config
//exports.setLightLevel     = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 8:; result=true;default:if (!result) break;                                                  if ( iArraySensorLightLevel[iSensorNumber] !== undefined ){           client.changeSensorConfig( iSensorNumber, { "lightlevel": iArraySensorLightLevel[iSensorNumber]                }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only Config
//exports.setDark           = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 8:; result=true;default:if (!result) break;                                                  if ( bArraySensorDark[iSensorNumber] !== undefined ){                 client.changeSensorConfig( iSensorNumber, { "dark": bArraySensorDark[iSensorNumber]                            }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only Config
//exports.setDaylight       = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 8:; result=true;default:if (!result) break;                                                  if ( bArraySensorDaylight[iSensorNumber] !== undefined ){             client.changeSensorConfig( iSensorNumber, { "daylight": bArraySensorDaylight[iSensorNumber]                    }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only Config
//exports.setStatus         = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 0:; result=true;default:if (!result) break;                                                  if ( iArraySensorStatus[iSensorNumber] !== undefined ){               client.changeSensorState(  iSensorNumber, { "status": iArraySensorStatus[iSensorNumber]                        }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Enabled State   
//exports.setLastupdated    = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) {  case 7:;case 10:; case 11:; result=true;default:if (!result) break;                              if ( sArraySensorLastupdated[iSensorNumber] !== undefined ){          client.changeSensorConfig( iSensorNumber, { "lastupdated": sArraySensorLastupdated[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only Config
//exports.setPresence       = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 6:; result=true;default:if (!result) break;                                                  if ( bArraySensorPresence[iSensorNumber] !== undefined ){             client.changeSensorConfig( iSensorNumber, { "presence": bArraySensorPresence[iSensorNumber]                    }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only Config
//exports.setTemperature    = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) {                                                                                                   if ( iArraySensorTemperature[iSensorNumber] !== undefined ){          client.changeSensorConfig( iSensorNumber, { "temperature": iArraySensorTemperature[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only Config
  exports.setOn             = function ( iSensorNumber, Value ){ if (iSensorNumber !== 0 ){                                                                                                                 if ( bArraySensorOn[iSensorNumber] !== undefined ){                   client.changeSensorState(  iSensorNumber, { "on": bArraySensorOn[iSensorNumber]                                }, function( err, result ){ if ( err) throw err; console.log(result); }); ;} }; };      //Enabled State   
//exports.setBattery        = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 1:;result=true;default:if (!result) break;                                                   if ( iArraySensorBattery[iSensorNumber] !== undefined ){              client.changeSensorConfig( iSensorNumber, { "battery": iArraySensorBattery[iSensorNumber]                      }, function( err, result ){ if ( err) throw err; console.log(result); }); ;} }; };     //Enabled State   
//exports.setConfigured     = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 2:;case 6:;case 7:;case 8:;case 9:;case 10:;case 11:;result=true;default:if (!result) break; if ( bArraySensorConfigured[iSensorNumber] !== undefined ){           client.changeSensorState(  iSensorNumber, { "configured": bArraySensorConfigured[iSensorNumber]                }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only state 
  exports.setReachable      = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 6:;case 7:;case 8:;result=true;default:if (!result) break;                                   if ( bArraySensorReachable[iSensorNumber] !== undefined ){            client.changeSensorState(  iSensorNumber, { "reachable": bArraySensorReachable[iSensorNumber]                  }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only state 
  exports.setAlert          = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 8:;result=true;default:if (!result) break;                                                   if ( sArraySensorAlert[iSensorNumber] !== undefined ){                client.changeSensorConfig( iSensorNumber, { "alert": sArraySensorAlert[iSensorNumber]                          }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Enabled State   
  exports.setTholdDark      = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 8:;result=true;default:if (!result) break;                                                   if ( iArraySensorTholdDark[iSensorNumber] !== undefined ){            client.changeSensorConfig( iSensorNumber, { "tholddark": iArraySensorTholdDark[iSensorNumber]                  }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Enabled State   
  exports.setTholdOffset    = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 2:;case 9:;result=true;default:if (!result) break;                                           if ( iArraySensorTholdOffset[iSensorNumber] !== undefined ){          client.changeSensorConfig( iSensorNumber, { "tholdoffset": iArraySensorTholdOffset[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Enabled State   
  exports.setLedindication  = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 6:;case 7:;case 8:;result=true;default:if (!result) break;                                   if ( bArraySensorLedindication[iSensorNumber] !== undefined ){        client.changeSensorConfig( iSensorNumber, { "ledindication": bArraySensorLedindication[iSensorNumber]          }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Enabled State   
  exports.setUsertest       = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 6:;case 7:;case 8:;result=true;default:if (!result) break;                                   if ( bArraySensorUsertest[iSensorNumber] !== undefined ){             client.changeSensorConfig( iSensorNumber, { "usertest": bArraySensorUsertest[iSensorNumber]                    }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Enabled State   
  exports.setSensitivity    = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 7:;result=true;default:if (!result) break;                                                   if ( iArraySensorSensitivity[iSensorNumber] !== undefined ){          client.changeSensorConfig( iSensorNumber, { "sensitivity": iArraySensorSensitivity[iSensorNumber]              }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Enabled State   
//exports.setSensitivitymax = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 7:;result=true;default:if (!result) break;                                                   if ( iArraySensorSensitivityMax[iSensorNumber]!== undefined ){        client.changeSensorConfig( iSensorNumber, { "sensitivitymax": iArraySensorSensitivityMax[iSensorNumber]        }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Read-Only state 
  exports.setSunsetoffset   = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 1:;result=true;default:if (!result) break;                                                   if ( iArraySensorSunriseoffset[iSensorNumber] !== undefined ){        client.changeSensorConfig( iSensorNumber, { "sunriseoffset": iArraySensorSunriseoffset[iSensorNumber]          }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Enabled State   
  exports.setUnriseoffset   = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 1:;result=true;default:if (!result) break;                                                   if ( iArraySensorSunsetoffset[iSensorNumber] !== undefined ) {        client.changeSensorConfig( iSensorNumber, { "sunsetoffset": iArraySensorSunsetoffset[iSensorNumber]            }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };     //Enabled State   
  exports.setPending        = function ( iSensorNumber, Value ){ result = false; switch (iSensorNumber) { case 6:;case 7:;case 8:;result=true;default:if (!result) break;                                   if ( sArraySensorPending[iSensorNumber] !== undefined ){              client.changeSensorConfig( iSensorNumber, { "pending": sArraySensorPending[iSensorNumber]                      }, function( err, result ){ if ( err) throw err; console.log(result); }); }; }; };      //Enabled State  



/**********\
| loadInfo |#####################################################################################################################################################################\
|                                                                                                                                                                                |
| - load variables from 1 sensor from disk                                                                                                                                       |
|                                                                                                                                                                                |
| Example: sensor.loadInfo(iSensorNumber)                                                                                                                                        |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
exports.loadInfo = function(iSensorNumber){
  //if (!fs.existsSync(pathhuesensorvalues + iSensorNumber + "/state"))
  var path;

  path = pathhuesensorvalues + iSensorNumber + "/manufacturername"      ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ sArrayLightManufacturerName[iSensorNumber] = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/modelid"               ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ sArraySensorModelId[iSensorNumber]         = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/name"                  ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ sArraySensorName[iSensorNumber]            = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/swversion"             ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ sArraySensorSwVersion[iSensorNumber]       = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/type"                  ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ sArraySensorType[iSensorNumber]            = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/uniqueid"              ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ sArraySensorUniqueId[iSensorNumber]        = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/state/buttonevent"     ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorButtonEvent[iSensorNumber]     = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/state/lightlevel"      ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorLightLevel[iSensorNumber]      = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/state/dark"            ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ bArraySensorDark[iSensorNumber]            = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/state/daylight"        ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ bArraySensorDaylight[iSensorNumber]        = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/state/status"          ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorStatus[iSensorNumber]          = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/state/lastupdated"     ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ sArraySensorLastupdated[iSensorNumber]     = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/state/presence"        ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ bArraySensorPresence[iSensorNumber]        = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/state/temperature"     ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorTemperature[iSensorNumber]     = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/state/on"              ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ bArraySensorOn[iSensorNumber]              = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/battery"        ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorBattery[iSensorNumber]         = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/configured"     ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ bArraySensorConfigured[iSensorNumber]      = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/reachable"      ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ bArraySensorReachable[iSensorNumber]       = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/alert"          ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ sArraySensorAlert[iSensorNumber]           = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/tholddark"      ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorTholdDark[iSensorNumber]       = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/tholdoffset"    ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorTholdOffset[iSensorNumber]     = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/ledindication"  ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ bArraySensorLedindication[iSensorNumber]   = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/usertest"       ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ bArraySensorUsertest[iSensorNumber]        = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/sensitivity"    ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorSensitivity[iSensorNumber]     = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/sensitivitymax" ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorSensitivityMax[iSensorNumber]  = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/sunsetoffset"   ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorSunsetoffset[iSensorNumber]    = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/sunriseoffset"  ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ iArraySensorSunriseoffset[iSensorNumber]   = data; }; }); };
  path = pathhuesensorvalues + iSensorNumber + "/config/pending"        ; if ( fs.existsSync( path ) ){ fs.readFile( path , function read(err, data) { if(err) { return console.log(err); }   if( data !== undefined){ sArraySensorPending[iSensorNumber]         = data; }; }); };

};



/****************\
| loadInfo - All |###############################################################################################################################################################\
|                                                                                                                                                                                |
| - loads all variables from all sensors from disk                                                                                                                               |
|                                                                                                                                                                                |
| Example: sensor.loadInfoAll()                                                                                                                                                  |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
exports.loadInfoAll = function(){
  //process.stdout.write('\n' + " Push Sensor Info...");
  var x = 1;
  loadInfoAllDo();

  function loadInfoAllDo(){
    if ( x > iArraySensorConnected.length ){ return; }
    sensor.loadInfo(iArraySensorConnected[x++]);
    setTimeout(loadInfoAllDo, 10);
  }
}



/**********\
| saveInfo |#####################################################################################################################################################################\
|                                                                                                                                                                                |
| - saves variables from 1 light from disk                                                                                                                                       |
|                                                                                                                                                                                |
| Example: sensor.saveInfo(iSensorNumber)                                                                                                                                        |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
exports.saveInfo = function(iSensorNumber){

  if (!fs.existsSync(pathhuesensorvalues + iSensorNumber + "/state")) { exec("/bin/mkdir -p " + pathhuesensorvalues + iSensorNumber + "/state" ); };
  if (!fs.existsSync(pathhuesensorvalues + iSensorNumber + "/state")) { exec("/bin/mkdir -p " + pathhuesensorvalues + iSensorNumber + "/config" ); };

  if ( sArraySensorManufacturerName[iSensorNumber] !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/manufacturername"      , sArraySensorManufacturerName[iSensorNumber] , function(err) { if(err) { return console.log(err); }; }); };              
  if ( sArraySensorModelId[iSensorNumber]          !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/modelid"               , sArraySensorModelId[iSensorNumber]          , function(err) { if(err) { return console.log(err); }; }); };              
  if ( sArraySensorName[iSensorNumber]             !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/name"                  , sArraySensorName[iSensorNumber]             , function(err) { if(err) { return console.log(err); }; }); };              
  if ( sArraySensorSwVersion[iSensorNumber]        !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/swversion"             , sArraySensorSwVersion[iSensorNumber]        , function(err) { if(err) { return console.log(err); }; }); };              
  if ( sArraySensorType[iSensorNumber]             !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/type"                  , sArraySensorType[iSensorNumber]             , function(err) { if(err) { return console.log(err); }; }); };              
  if ( sArraySensorUniqueId[iSensorNumber]         !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/uniqueid"              , sArraySensorUniqueId[iSensorNumber]         , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorButtonEvent[iSensorNumber]      !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/state/buttonevent"     , iArraySensorButtonEvent[iSensorNumber]      , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorLightLevel[iSensorNumber]       !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/state/lightlevel"      , iArraySensorLightLevel[iSensorNumber]       , function(err) { if(err) { return console.log(err); }; }); };              
  if ( bArraySensorDark[iSensorNumber]             !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/state/dark"            , bArraySensorDark[iSensorNumber]             , function(err) { if(err) { return console.log(err); }; }); };              
  if ( bArraySensorDaylight[iSensorNumber]         !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/state/daylight"        , bArraySensorDaylight[iSensorNumber]         , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorStatus[iSensorNumber]           !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/state/status"          , iArraySensorStatus[iSensorNumber]           , function(err) { if(err) { return console.log(err); }; }); };              
  if ( sArraySensorLastupdated[iSensorNumber]      !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/state/lastupdated"     , sArraySensorLastupdated[iSensorNumber]      , function(err) { if(err) { return console.log(err); }; }); };              
  if ( bArraySensorPresence[iSensorNumber]         !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/state/presence"        , bArraySensorPresence[iSensorNumber]         , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorTemperature[iSensorNumber]      !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/state/temperature"     , iArraySensorTemperature[iSensorNumber]      , function(err) { if(err) { return console.log(err); }; }); };              
  if ( bArraySensorOn[iSensorNumber]               !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/state/on"              , bArraySensorOn[iSensorNumber]               , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorBattery[iSensorNumber]          !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/battery"        , iArraySensorBattery[iSensorNumber]          , function(err) { if(err) { return console.log(err); }; }); };              
  if ( bArraySensorConfigured[iSensorNumber]       !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/configured"     , bArraySensorConfigured[iSensorNumber]       , function(err) { if(err) { return console.log(err); }; }); };              
  if ( bArraySensorReachable[iSensorNumber]        !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/reachable"      , bArraySensorReachable[iSensorNumber]        , function(err) { if(err) { return console.log(err); }; }); };              
  if ( sArraySensorAlert[iSensorNumber]            !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/alert"          , sArraySensorAlert[iSensorNumber]            , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorTholdDark[iSensorNumber]        !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/tholddark"      , iArraySensorTholdDark[iSensorNumber]        , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorTholdOffset[iSensorNumber]      !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/tholdoffset"    , iArraySensorTholdOffset[iSensorNumber]      , function(err) { if(err) { return console.log(err); }; }); };              
  if ( bArraySensorLedindication[iSensorNumber]    !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/ledindication"  , bArraySensorLedindication[iSensorNumber]    , function(err) { if(err) { return console.log(err); }; }); };              
  if ( bArraySensorUsertest[iSensorNumber]         !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/usertest"       , bArraySensorUsertest[iSensorNumber]         , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorSensitivity[iSensorNumber]      !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/sensitivity"    , iArraySensorSensitivity[iSensorNumber]      , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorSensitivityMax[iSensorNumber]   !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/sensitivitymax" , iArraySensorSensitivityMax[iSensorNumber]   , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorSunsetoffset[iSensorNumber]     !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/sunsetoffset"   , iArraySensorSunsetoffset[iSensorNumber]     , function(err) { if(err) { return console.log(err); }; }); };              
  if ( iArraySensorSunriseoffset[iSensorNumber]    !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/sunriseoffset"  , iArraySensorSunriseoffset[iSensorNumber]    , function(err) { if(err) { return console.log(err); }; }); };              
  if ( sArraySensorPending[iSensorNumber]          !== undefined ){ fs.writeFile( pathhuesensorvalues + iSensorNumber + "/config/pending"        , sArraySensorPending[iSensorNumber]          , function(err) { if(err) { return console.log(err); }; }); };              
};



/***************\
| setInfo - All |################################################################################################################################################################\
|                                                                                                                                                                                |
| - saves all variables from all sensors to disk                                                                                                                                 |
|                                                                                                                                                                                |
| Example: sensor.saveInfoAll()                                                                                                                                                  |
|                                                                                                                                                                                |
\********************************************************************************************************************************************************************************/
exports.saveInfoAll = function(){
  //process.stdout.write('\n' + " Fetch Sensor Info...");
  var x = 1;
  saveInfoAllDo();

  function saveInfoAllDo(){
    if ( x > iArraySensorConnected.length ){ return; }
    sensor.saveInfo(iArraySensorConnected[x++]);
    setTimeout(saveInfoAllDo, 10);
  }
}
